name: AndroidBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      # Create GitHub Release (only on push to main, not on PR)
      - name: Create GitHub Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          name: "ALPHA v0.1-${{ steps.timestamp.outputs.timestamp }}"
          tag_name: "v0.1-${{ steps.timestamp.outputs.timestamp }}"
          prerelease: true
          draft: false
          files: app/build/outputs/apk/debug/app-debug.apk
          body: |
            ### ⚠️ EARLY DEVELOPMENT STAGE ⚠️
            
            This is an automatically generated alpha release from the latest commit.
            
            ### Known limitations:
            - This is an experimental build with limited testing
            - Features may be incomplete or non-functional
            - Use at your own risk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
